# Generated by Django 5.2.6 on 2025-09-16 19:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_trashbinentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='absences',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='student',
            name='areas_for_improvement',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='student',
            name='attended_sessions',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='avg_scores',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='student',
            name='awards',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='student',
            name='certifications',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='student',
            name='contributions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='student',
            name='current_status',
            field=models.CharField(choices=[('active', 'Active'), ('graduated', 'Graduated'), ('dropped', 'Dropped'), ('on_hold', 'On Hold')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='student',
            name='enrollment_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='student',
            name='graduation_eligibility',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='hackathons_attended',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='student',
            name='mentor_comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='student',
            name='next_steps',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='student',
            name='participation_score',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='student',
            name='peer_reviews',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='student',
            name='phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='student_photos/'),
        ),
        migrations.AddField(
            model_name='student',
            name='progress_graph_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='project_completion_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='student',
            name='strengths',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='student',
            name='student_id',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='student',
            name='total_sessions',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
