# Generated by Django 5.2.6 on 2025-09-18 09:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0004_student_absences_student_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivitiesAchievements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hackathons_attended', models.TextField(blank=True)),
                ('awards', models.TextField(blank=True)),
                ('contributions', models.TextField(blank=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.student')),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_sessions', models.PositiveIntegerField(default=0)),
                ('attended_sessions', models.PositiveIntegerField(default=0)),
                ('absences', models.PositiveIntegerField(default=0)),
                ('participation_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.student')),
            ],
        ),
        migrations.CreateModel(
            name='EnrollmentDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('trainee', 'Trainee'), ('internee-university', 'Internee (University)'), ('internee-highschool', 'Internee (High School)')], max_length=30)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('program', models.CharField(choices=[('iot', 'IoT'), ('sod', 'SoD')], max_length=10)),
                ('level', models.CharField(max_length=50)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.student')),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mentor_comments', models.TextField(blank=True)),
                ('peer_reviews', models.TextField(blank=True)),
                ('strengths', models.TextField(blank=True)),
                ('areas_for_improvement', models.TextField(blank=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.student')),
            ],
        ),
        migrations.CreateModel(
            name='PerformanceGrades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avg_scores', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('project_completion_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('certifications', models.TextField(blank=True)),
                ('progress_graph_data', models.JSONField(blank=True, null=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.student')),
            ],
        ),
        migrations.CreateModel(
            name='StatusRecommendations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_status', models.CharField(choices=[('active', 'Active'), ('graduated', 'Graduated'), ('dropped', 'Dropped'), ('on_hold', 'On Hold')], default='active', max_length=20)),
                ('next_steps', models.TextField(blank=True)),
                ('graduation_eligibility', models.BooleanField(default=False)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('address', models.TextField(blank=True)),
                ('enrollment_date', models.DateField(default=django.utils.timezone.now)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='student_photos/')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.student')),
            ],
        ),
    ]
