# Generated by Django 5.2.6 on 2025-09-18 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0005_activitiesachievements_attendanceparticipation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='student',
        ),
        migrations.RemoveField(
            model_name='student',
            name='absences',
        ),
        migrations.RemoveField(
            model_name='student',
            name='areas_for_improvement',
        ),
        migrations.RemoveField(
            model_name='student',
            name='attended_sessions',
        ),
        migrations.RemoveField(
            model_name='student',
            name='avg_scores',
        ),
        migrations.RemoveField(
            model_name='student',
            name='awards',
        ),
        migrations.RemoveField(
            model_name='student',
            name='certifications',
        ),
        migrations.RemoveField(
            model_name='student',
            name='contributions',
        ),
        migrations.RemoveField(
            model_name='student',
            name='current_status',
        ),
        migrations.RemoveField(
            model_name='student',
            name='graduation_eligibility',
        ),
        migrations.RemoveField(
            model_name='student',
            name='hackathons_attended',
        ),
        migrations.RemoveField(
            model_name='student',
            name='mentor_comments',
        ),
        migrations.RemoveField(
            model_name='student',
            name='next_steps',
        ),
        migrations.RemoveField(
            model_name='student',
            name='participation_score',
        ),
        migrations.RemoveField(
            model_name='student',
            name='peer_reviews',
        ),
        migrations.RemoveField(
            model_name='student',
            name='progress_graph_data',
        ),
        migrations.RemoveField(
            model_name='student',
            name='project_completion_rate',
        ),
        migrations.RemoveField(
            model_name='student',
            name='strengths',
        ),
        migrations.RemoveField(
            model_name='student',
            name='total_sessions',
        ),
        migrations.DeleteModel(
            name='EnrollmentDetail',
        ),
        migrations.DeleteModel(
            name='StudentProfile',
        ),
    ]
